### ISSUE TITLE
"500error" occurred in importing attrib-basic-ep

### ISSUE THREAD

**Issue by zswll2** [mc12345678/EasyPopulate-4.0#55]
![4](https://user-images.githubusercontent.com/37688676/102685815-2f015280-421e-11eb-995c-f89771fb4a7b.png)
![3](https://user-images.githubusercontent.com/37688676/102685817-30327f80-421e-11eb-9e2a-c5284cf23813.png)
![1](https://user-images.githubusercontent.com/37688676/102685819-31fc4300-421e-11eb-9ef4-5faa1abeec23.png)
![2](https://user-images.githubusercontent.com/37688676/102685821-332d7000-421e-11eb-90da-591ff16420c4.png)

**Comment by mc12345678** [comment]
How many records are in the file?
Has it been split yet so that fewer records per file are processed?
What version of EP4?
Already can tell that using Zen Cart 1.5.7x, though would be good to also know which sub-version.

**Comment by zswll2** [comment]
> How many records are in the file?  
> Has it been split yet so that fewer records per file are processed?
**>>I tested that there was only one piece of data in the imported file, and there was this problem only when importing attrib-basic-ep. All other types of data were normal.**
> What version of EP4?
**>>Easy Populate 4.0.37.10 - 02-08-2017**
> Already can tell that using Zen Cart 1.5.7x, though would be good to also know which sub-version.
**>>Zen Cart 1.5.7**

My website log;
172.69.33.107 - - [20/Dec/2020:13:42:07 +0800] "POST /shine_jack/index.php?cmd=easypopulate_4 HTTP/1.1" 500 23 "https://www.xxx.com/shine_jack/index.php?cmd=easypopulate_4" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

172.69.33.107 - - [20/Dec/2020:13:42:21 +0800] "POST /shine_jack/index.php?cmd=easypopulate_4 HTTP/1.1" 200 11571 "https://www.xxx.com/shine_jack/index.php?cmd=easypopulate_4" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

![1](https://user-images.githubusercontent.com/37688676/102706129-4ac23280-42ca-11eb-84b9-4a9d9e2ef110.png)

**Comment by mc12345678** [comment]
This problem should have been corrected by commit: a417f116b2bd5bc90e51101b71739b9abe24a45a

Closing issue. Open again if that did not resolve the issue.
